name: Native Linux

on:
  pull_request:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  native:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
        rust: [ 1.59.0 ]

    runs-on: ${{matrix.os}}
    env:
      RUST_VERSION: ${{matrix.rust}}
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 2G
      SCCACHE_DIR: $PATH/.cache/sccache

    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/workflows/setup-cache.yml
      with:
        rust: ${{matrix.rust}}
        key: native

    - name: Native script
      run: .travis/regular-tests.sh
      env:
        SHORT: yes

    - name: Stop sccache server
      run: sccache --stop-server || true
